### ISSUE TITLE
Datasheet

### ISSUE THREAD

**Issue by ikey-ru** [tuupola/axp173#1]
Hi.
Do you have a datasheet in English for axp173? 

Sometimes we come across batches of microcircuits that do not give out +3.3 to power the processor. And we can't run them. It is not clear whether the chip should supply power immediately before initialization, or it can remember the settings after a power reset and from the factory it is not configured to output 3.3V 

Regards, Pavel

**Comment by tuupola** [comment]
[AXP173 Datasheet v1.12_cn.zh-CN.en.pdf](https://github.com/tuupola/axp173/files/8003577/AXP173.Datasheet.v1.12_cn.zh-CN.en.pdf)

I don't remember where I found this. It might be machine translated from Chinese to English.

**Comment by ikey-ru** [comment]
Thanks!
